services:
  spring-boot-app:
    networks:
      - app-network  # Сервис для Spring Boot приложения
    build:
      context: ./spring-boot-app  # Указываем путь к Dockerfile Spring Boot
    ports:
      - "8080:8080"  # Пробрасываем порт 8080 на хост

    environment:
      # - PYTHON_APP_URL=http://python-app:5000

      - PYTHON_SERVICE_URL=http://python-app:5000/process-excel
  # Переменная окружения для URL Python-приложения

  python-app:
    networks:
      - app-network
    build:
      context: ./AutoCadDXF
      dockerfile: Dockerfile
    container_name: python-app
    ports:
      - "5000:5000"

networks:
  app-network:
    driver: bridge